### ISSUE TITLE
trademark policy

### ISSUE THREAD

**Issue by glycerine** [glycerine/vj#3]
In honoring the trademark policy that the veracity 2.5 source bundle includes, I wrote to Eric Sink requesting permission to mention Veracity and this project's relationship to it (as a derivative) in the README.

Eric, could you reply here (rather than have me paste in your email)? Thanks!

**Comment by ericsink** [comment]
Permission granted.  :-)

**Comment by glycerine** [comment]
:-) Thanks Eric.
